[project]
name = "123456"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "troubles", email = "ritar_09@mail.ru" }
]
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.3",
    "mysql-connector-python<9.0.0",
]

[project.scripts]
123456 = "123456:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
